- id: '1688763993090'
  alias: Sergiu Switch Brightness Up Hold
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: brightness_move_up
    discovery_id: 0xf4b3b1fffe2ac039 action_brightness_move_up
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 254
      transition: 1
    target:
      area_id: sergiu_room
- id: '1688766152849'
  alias: Sergiu Switch Brightness Down Hold
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: brightness_move_down
    discovery_id: 0xf4b3b1fffe2ac039 action_brightness_move_down
  action:
  - service: light.turn_off
    data:
      transition: 1
    target:
      area_id: sergiu_room
  mode: single
- id: '1688766392958'
  alias: Sergiu Switch Brightness Up Click
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: 'on'
    discovery_id: 0xf4b3b1fffe2ac039 action_on
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 20
      transition: 1
    target:
      area_id: sergiu_room
  mode: single
- id: '1688769768191'
  alias: Sergiu Switch Brightness Down Click
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: 'off'
    discovery_id: 0xf4b3b1fffe2ac039 action_off
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -20
      transition: 1
    target:
      area_id: sergiu_room
  mode: single
- id: '1688770813710'
  alias: Sergiu Switch Left Hold
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: arrow_left_hold
    discovery_id: 0xf4b3b1fffe2ac039 action_arrow_left_hold
  condition: []
  action:
  - service: light.turn_on
    data:
      color_temp: 153
    target:
      area_id: sergiu_room
  mode: single
- id: '1688770884298'
  alias: Sergiu Switch Left Hold
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6c879a1195b5301b077b3aab53dee978
    type: action
    subtype: arrow_right_hold
    discovery_id: 0xf4b3b1fffe2ac039 action_arrow_right_hold
  condition: []
  action:
  - service: light.turn_on
    data:
      color_temp: 500
    target:
      area_id: sergiu_room
  mode: single
