homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - fd00::/8

logger:
  default: info

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 172.22.0.2

automation: !include automations.yaml

# Enable history for graphs and logging
history:
